<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:tns="http://itq.edu/multiplication" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
name="multiplication" 
targetNamespace="http://itq.edu/multiplication">
  <wsdl:types>
    <xsd:schema targetNamespace="http://itq.edu/multiplication">
    	<xsd:include schemaLocation="multiplication.xsd"></xsd:include>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="generateTableRequest">
    <wsdl:part element="tns:Request" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="generateTableResponse">
    <wsdl:part element="tns:Response" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="multiplicationPortType">
    <wsdl:operation name="generateTable">
      <wsdl:input message="tns:generateTableRequest"/>
      <wsdl:output message="tns:generateTableResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="multiplicationBinding" type="tns:multiplicationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="generateTable">
      <soap:operation soapAction="http://itq.edu/multiplication/generateTable"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="multiplication">
    <wsdl:port binding="tns:multiplicationBinding" name="multiplicationSOAP">
      <soap:address location="http://localhost:8080/multiplication"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
